### ISSUE TITLE
[rust_analyzer] initalizationOptions causing ra_lsp_server an error

### ISSUE THREAD

**Issue by KokaKiwi** [neovim/nvim-lsp#94] opened 2020-01-15 19:19 UTC
Because of how vim `json_encode` transform vim data into JSON data, the lua value `{}` which is the default value for `init_options` is being encoded into an empty JSON array.
But `ra_lsp_server` expect to receive a JSON map for decoding the init options and emit an error: `failed to deserialize config: invalid length 0, expected struct ServerConfig with 12 elements` when receiving an empty initializationOptions by vim.lsp.
Hopefully rust-analyzer handle this error by just logging it and sticking with default values, but still the error message appears, which can be actually confusing.

**Comment by justinmk** [comment] 2020-01-18 23:42
> lua value `{}` which is the default value for `init_options` is being encoded into an empty JSON array.

This can be fixed by setting it to `vim.empty_dict()`. Just need someone to send a PR doing that.

**Comment by KokaKiwi** [comment] 2020-01-19 03:04
I think default to that would be good, as the LSP spec says `initOptions` has to be a dictionary anyway, so even if implementations actually mainly don't mind about this, defaulting to what the specs say seems to be the correct way of handling this imho

**Comment by matu3ba** [comment] 2020-01-29 16:43
Changing in lua/nvim_lsp/skeleton.lua
<code>init_options = {};</code> to
<code>init_options = vim.empty_dict();</code>
did **not solve the issue**.
I directly changed the git folder in plugged and used  
`lua require'nvim_lsp'.rust_analyzer.setup{}` in *init.vim*.

`call nvim_lsp#setup("rust_analyzer", {})` returns `unknown function`, so it should be removed from the docs.
What am I missing here?

**Comment by anderejd** [comment] 2020-01-29 18:18
@matu3ba Did you get it to work? If yes, I would very much appreciate a full example of how to do it.

**Comment by matu3ba** [comment] 2020-01-29 18:36
Sorry, somehow it works. I was very confused by the message, but the message shortly thereafter disappears.

**Comment by matu3ba** [comment] 2020-01-29 19:00
With the described 1-line [PR](https://github.com/neovim/nvim-lsp/pull/107) added, it works.

**Comment by justinmk** [comment] 2020-01-31 08:10
> `call nvim_lsp#setup("rust_analyzer", {})` returns `unknown function`, so it should be removed from the docs.

@matu3ba where are you seeing that? It was removed from all docs that I know of, weeks ago.

**Comment by matu3ba** [comment] 2020-02-02 00:18
@justinmk you are correct.

**Comment by tuxsoy** [comment] 2020-02-10 06:32
Can someone please double check? I still have this issue.

**Comment by justinmk** [comment] 2020-02-10 07:01
@tuxsoy always need to know exact version of Nvim and this plugin.

**Comment by tuxsoy** [comment] 2020-02-10 22:27
@justinmk I'm using the appimage release of neovim (`NVIM v0.5.0-363-g31614d3eb`) with nvim-lsp commit 42385db. The error message is:

```
LSP[rust_analyzer] failed to deserialize config: invalid length 0, expected struct ServerConfig with 12 elements
```

Reverting to commit b4f4b72 does not solve the issue either.

Commenting the following lines fixes the issue for me, so the problem is probably on these lines:
https://github.com/neovim/nvim-lsp/blob/42385dbf6a5eac40da213322fdd3037588eede56/lua/nvim_lsp/configs.lua#L102-L103

**Comment by h-michael** [comment] 2020-02-10 23:25
OK, I'll check it later.

**Comment by h-michael** [comment] 2020-02-11 00:58
@KokaKiwi @matu3ba  @tuxsoy 
Would you try [this branch](#121)?

**Comment by matu3ba** [comment] 2020-02-11 11:45
> @KokaKiwi @matu3ba @tuxsoy
> Would you try [this branch](#121)?

This removes the error message and shows "LSP[rust_analyzer][Info] workspace loaded, 12 rust packages".
Did try on the old and current nightly neovim appimage.

**Comment by halzy** [comment] 2020-02-13 04:17
> I think [neovim/neovim#11864](https://github.com/neovim/neovim/pull/11864) will solve this.

I manually patched the last nightly (v0.5.0-372-g68de6b17b) with the 5 lines ([here](https://github.com/h-michael/neovim/commit/417fc6ccf78801aef79a8731c5a85db6b12cd407#diff-7f472431a1463bbeec031cd66114173eR23)) and it didn't fix the error. Also tried it in combination with [pull 121](https://github.com/neovim/nvim-lsp/pull/121) with no success.

**Comment by h-michael** [comment] 2020-02-13 05:00
@halzy
It works fine in my environment.
Would you show me this command result?

`:lua print(vim.inspect(vim.deepcopy(vim.empty_dict())))`

**Comment by halzy** [comment] 2020-02-13 13:42
This is the result: 
`E5105: Error while calling lua chunk: [string "<VimL compiled string>"]:1: attempt to call field 'empty_dict' (a nil value)`

I had modified the file that were unzip'd with neovim's nightly (osx) and had used Plug to install (git fetch) the nvim-lsp directory, to which I added the other repo as a remote and checked the branch out that the pull request was for.

**Comment by halzy** [comment] 2020-02-13 13:44
Ah, shoot. I was in the wrong neovim for that command you mentioned.

The actual result: `{}`

**Comment by h-michael** [comment] 2020-02-14 00:47
@halzy 
> Ah, shoot. I was in the wrong neovim for that command you mentioned.

> The actual result: {}

That result is not expected.
Expected behavior is `vim.empty_dict()`.
You may have something wrong build.

**Comment by halzy** [comment] 2020-02-14 18:12
Versions:
NeoVIM: `NVIM v0.5.0-374-gd9657b3ae`
nvim-lsp: `:Plug 'h-michael/nvim-lsp', { 'branch': 'ra-server' }`

With the nvim-osx files expanded in my home dir patched with: 
https://github.com/neovim/neovim/pull/11864/files#diff-7f472431a1463bbeec031cd66114173e

All other NeoVim install have been removed from my system.
`:lua print(vim.inspect(vim.deepcopy(vim.empty_dict())))`
still reports: `{}`

@h-michael Am I missing a step? is there a cache of the original `~/nvim-osx64/share/nvim/runtime/lua/vim/shared.lua` file somewhere?

**Comment by halzy** [comment] 2020-02-14 22:34
I just ran a git bisect on the issue. `3062676b5c846174996bfd7ee746b3e5b7176d5b` is the commit that introduced the error.

**Closed** 2020-02-15 17:10 UTC
Labels: bug, good first issue, help wanted

**Comment by bfredl** [comment] 2020-02-15 17:24
This got closed by automatic github action. If issues persist we can reopen it.

**Comment by h-michael** [comment] 2020-02-16 03:16
@halzy Try nightly Neovim. My fixes are included.

**Comment by halzy** [comment] 2020-02-18 03:15
Issue has been resolved. Thank you!
