### ISSUE TITLE
[gopls] rename does not work

### ISSUE THREAD

**Issue by urandom** [neovim/nvim-lsp#134] opened 2020-02-20 08:41 UTC
- `nvim --version`:
<pre>
NVIM v0.5.0-b353a5c
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200217-43799-1f6xoye/build/config -I/tmp/neovim-20200217-43799-1f6xoye/src -I/usr/local/include -I/tmp/neovim-20200217-43799-1f6xoye/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200217-43799-1f6xoye/build/src/nvim/auto -I/tmp/neovim-20200217-43799-1f6xoye/build/include
Compiled by viktor.kojouharov@Viktors-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-b353a5c/share/nvim"

Run :checkhealth for more info
</pre>
- nvim-lsp version:
8c78ca4

- What language server(If the problem is related to a specific language server):
gopls

- Operating system/version:
macosx

- Terminal name/version:
iterm2 3.3.8
- `$TERM`:
xterm-256color

### How to reproduce the problem from neovim startup
lua vim.lsp.buf.rename() in an unmodified file

### Actual behaviour
The following message is printed: 
Buffer  file:///some/file.go  newer than edits.

No actual renaming occurs.
The file isn't modified.

Note, renaming behavior works with vscode.

### Expected behaviour
Renaming occurs

**Comment by mfussenegger** [comment] 2020-02-20 22:09
I think this might be fixed with the buffer version change (https://github.com/neovim/neovim/pull/11607/commits/ff421cfbccfeb95920f5ce17d4898a4262b3dd69) in https://github.com/neovim/neovim/pull/11607

**Comment by urandom** [comment] 2020-02-20 23:07
If I'm running on NVIM v0.5.0-388-gab12a2294, which according to AUR is from 20200219, wouldn't I already have this change?

**Comment by Jesse-Bakker** [comment] 2020-02-21 11:13
@urandom the referenced commit is part of a larger PR adding code actions, which is not merged yet. I will see if I can extract it to a separate PR, as this is a useful change for most parts of the protocol dealing with edits

**Comment by urandom** [comment] 2020-02-26 11:32
fyi, tested https://github.com/neovim/neovim/pull/11927. renaming works with that change

**Comment by h-michael** [comment] 2020-03-17 01:38
@urandom May I close this issue?

**Comment by urandom** [comment] 2020-03-17 08:58
I'll install the next nightly which will contain the pull request and give it another test, then come back

**Comment by urandom** [comment] 2020-03-17 20:52
Unfortunately, the error still occurs. I was able to rename a few things, but after that, the same error is being shown.

**Comment by donotnoot** [comment] 2020-03-18 21:57
I tried the fix, and I'm experiencing the same as urandom, it stops working after a while.

**Comment by h-michael** [comment] 2020-03-19 05:38
@urandom @donotnoot 
I can't reproduce it.
Would you show me a test project and a config?

**Comment by urandom** [comment] 2020-03-19 09:05
@h-michael 
Consider the following dummy code:
https://play.golang.org/p/N9sO9cbwz1d

Rename the first variable `resp` to something, then save. If you try to rename the `err` variable afterwards (or anything else for that matter), you'd get an error. It seems the problem is tied to saving the buffer.

**Comment by Jesse-Bakker** [comment] 2020-03-19 13:26
> @h-michael
> Consider the following dummy code:
> https://play.golang.org/p/N9sO9cbwz1d
> 
> Rename the first variable `resp` to something, then save. If you try to rename the `err` variable afterwards (or anything else for that matter), you'd get an error. It seems the problem is tied to saving the buffer.

When I try to reproduce the bug, I get a segfault in gopls on the second rename. Is that the error you are experiencing, or is it still just the "buffer version" one? Also, what version of gopls are you using?

I have possibly found the source of the bug, but I need to investigate a bit more using a setup closer to yours.

**Comment by urandom** [comment] 2020-03-19 15:18
@Jesse-Bakker  it's just the buffer version one. Gopls is at 0.3.3. It seems to always be reproducible after the file has been saved, regardless of whether there were renames before.

**Comment by h-michael** [comment] 2020-03-20 01:30
@urandom I could reproduce it. I'll investigate the cause.

**Comment by Jesse-Bakker** [comment] 2020-03-20 09:49
I found out why I got a segfault. It happens when renaming the `err` variable to `error`, which is a built-in interface. Will file a bug in the golang project.

With:
```
NVIM v0.5.0-418-g87d892afa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-d39de692-a323-45a4-b941-efab8add0571

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
and the posted snippet, I cannot reproduce the bug. Renaming just works.

**Closed** 2020-04-25 12:58 UTC
Labels: bug

**Comment by mawkler** [comment] 2024-06-12 08:13
I've started seeing this issue again. I'm on `v0.11.0-dev-164+g3a1515bfe`. It seems to be only occur consistently in only some Go files, not sure why. Rename doesn't work, code-actions don't work in those Go-files.
